### PR TITLE
Use test-unit-ruby-core instead of deep-copy from ruby repository

### PR DESCRIPTION
**Pull request by hsbt**
I and @nobu prepared https://github.com/ruby/test-unit-ruby-core for `test-unit` with `EnvUtil`.

We should remove related files from this repository.

### CODE REVIEW

**Comment by hsbt** [comment]
I'm not sure why Ruby 3.2 crashed.

https://github.com/ruby/strscan/actions/runs/6584775176/job/17889936696

**Comment by kou** [comment]
Because strscan in Ruby 3.2 not built strscan isn't used.
#61 isn't included in strscan in Ruby 3.2.

**Review by kou — APPROVED** [review]
The crash isn't related to this change.

**Comment by hsbt** [comment]
👍  Thanks for merging this.

**Pull request merged**
