### PR TITLE
Skip installation test with failing environment

### PR DESCRIPTION
**Pull request by hsbt**
I'm not sure why they are failing.

### CODE REVIEW

**Comment by kou** [comment]
We need to use newer version than strscan in the Ruby master.

**Comment by hsbt** [comment]
But they are completely broken

https://github.com/ruby/strscan/runs/4529866953?check_suite_focus=true

**Comment by kou** [comment]
https://github.com/ruby/strscan/actions/runs/1586405950

**Comment by hsbt** [comment]
Thanks.

Do you have a reason why you close this without discussion? I felt "contribution is not welcome" from you.

**Comment by kou** [comment]
Ah, sorry.
It was just caused automatically by "fix GH-28" in commit message of my fix: https://github.com/ruby/strscan/commit/4104fae88f9c73e187e9a1daa0f0ba5d662211ed

**Comment by hsbt** [comment]
Oh, I understood. I also sorry to blame you.

**Pull request closed without merging**
