### PR TITLE
Introduce an adapter from joni 2.1 to 2.2

### PR DESCRIPTION
**Pull request by headius**
JOni 2.2 will hide these public fields and the direct constructors for Region, so these adapters will bridge the gap until the new API is widely available. The adapter and calls to it can be removed once JRuby has shipped a few releases of 9.4 (and possibly 9.3) with the updated JOni.

### CODE REVIEW

**Comment by headius** [comment]
See https://github.com/jruby/jruby/pull/7620 which moves JRuby to the new API, https://github.com/jruby/joni/pull/58 and https://github.com/jruby/joni/pull/60 which introduce the API into joni, and https://github.com/jruby/joni/pull/59 which will remove access to the public fields and constructors in joni 2.2.

**Comment by headius** [comment]
This will not build cleanly until JRuby is released with the updated joni API. Merge and release after JRuby 9.4.1.

**Review by kou — APPROVED** [review]
+1

You can merge this after JRuby 9.4.1 release.

**Comment by headius** [comment]
This now builds cleanly and only fails the one known failure on Windows. Merging!

**Comment by headius** [comment]
@kou This is ready for a release any time!

**Comment by kou** [comment]
Done!

**Pull request merged**
